services:
  - type: web
    name: stata-backend
    runtime: image
    repo: https://github.com/ostia456/stata_backend
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
      - key: MAX_FILE_SIZE_MB
        value: 200
      - key: MAX_ROWS_TO_LOAD
        value: 10000
      - key: RENDER
        value: true
    healthCheckPath: /api/v1/health